import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AppProviders from '@/components/providers/AppProviders'
import { Toaster } from '@/components/ui/sonner'
import AuthProviders from '@/components/providers/AuthProviders'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <AuthProviders>
          <AppProviders>
            {children}
            <Toaster richColors />
          </AppProviders>
        </AuthProviders>
      </body>
    </html>
  )
}
